#ifndef HELENA_DEPENDENCIES_ENET_HPP
#define HELENA_DEPENDENCIES_ENET_HPP

#define ENET_IMPLEMENTATION
#define ENET_FEATURE_ADDRESS_MAPPING

#include <enet/enet.h>

#endif // HELENA_DEPENDENCIES_ENET_HPP