name: Build

on: [push]

jobs:
  ubuntu:
    name: "Ubuntu"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build: [Debug, Release]
        compiler: [Clang, GCC]
        include:
          - compiler: Clang
            binary: clang++-13
            install: |
              sudo wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
              sudo apt-add-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-13 main"
              sudo apt install -y clang-13
              sudo apt upgrade
          - compiler: GCC
            binary: g++-11
            install:
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install compiler
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt update
          sudo apt install -y g++-11 cmake ninja-build
          ${{ matrix.install }}
          sudo apt upgrade
      - name: Configure
        env:
          CXX: ${{ matrix.binary }}
        run: |
          cmake . -B Build -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.build }}
      - name: Build
        run: |
          cmake --build Build
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Helena (${{ matrix.compiler }} - ${{ matrix.build }})
          path: ${{ github.workspace }}/Bin/Bin/Helena
          if-no-files-found: error
  windows:
    name: "Windows"
    runs-on: windows-latest
    strategy:
      matrix:
        build: [Debug, Release]
        compiler: [MSVC, Clang]
        include:
          - compiler: MSVC
            toolset: -T"v142"
          - compiler: Clang
            toolset: -T"ClangCL"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.10.0
      - name: Configure
        run: |
          cmake . -B Build -G "Visual Studio 17 2022" -A x64 ${{ matrix.toolset }}
      - name: Build
        run: |
          cmake --build Build --config ${{ matrix.build }}
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Helena (${{ matrix.compiler }} - ${{ matrix.build }})
          path: ${{ github.workspace }}/Bin/Bin/Helena.exe
          if-no-files-found: error








